import React from 'react'

const About = () => {
  return (
    <div>
      <h1>ABOUT US</h1>
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis, vitae accusamus! Saepe laudantium, enim ducimus odit optio ex. Voluptates aliquam eligendi officia est quas cupiditate sit quis, repellat reiciendis minima tenetur, illum odio provident debitis. Perferendis aut fuga totam doloribus laboriosam optio deleniti repudiandae, rerum ducimus officiis eligendi dolore sint.
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque iste dolores sequi, nemo at cum ex excepturi veniam dolor, atque culpa inventore iusto veritatis facere harum ipsum quasi possimus maiores corrupti perspiciatis quos, corporis natus nam repudiandae? Eligendi debitis ducimus vero obcaecati ex, blanditiis voluptatum! Debitis incidunt eum praesentium, quasi quod sunt. Alias omnis nesciunt recusandae eius eum distinctio molestias totam quis commodi sunt tempore, sint praesentium ab! Ea esse, quia eaque id nostrum cum molestiae unde vitae. Nobis delectus obcaecati labore perferendis commodi quos aliquid molestias officia error? Rerum, cupiditate perspiciatis quidem quae iusto qui, saepe beatae ab delectus, eum aliquid dolorum soluta reiciendis perferendis nam alias culpa quos eveniet nulla laborum fugiat. Expedita aut beatae consectetur exercitationem alias voluptates, rerum error sit, assumenda provident accusamus nemo veritatis! Accusantium enim illo quaerat consectetur ratione soluta quia officiis sed inventore debitis maiores atque, dignissimos, aspernatur, ipsam nostrum. Quae aliquid neque sequi, distinctio quisquam harum eaque ex natus perspiciatis consequatur, nostrum, in facilis autem mollitia ratione modi incidunt maiores tempore dolor velit enim excepturi? Culpa ullam deleniti enim nemo. Omnis necessitatibus amet quae, ducimus similique magnam quis sint distinctio vel dicta asperiores quidem voluptate magni ut? Voluptate minus fugiat est, earum doloribus suscipit molestias vitae porro necessitatibus veniam aperiam natus sequi explicabo dicta quam rem voluptates temporibus. Amet ratione nemo quo illo incidunt, adipisci culpa doloremque nisi asperiores. Officia autem dolorum iusto ullam debitis impedit soluta in molestiae excepturi? Cum consectetur, ipsa voluptates magni quibusdam dolor magnam, ratione, necessitatibus laborum sint optio aliquid exercitationem explicabo at quae quas? Id iste nobis eum dicta, veritatis ipsa aliquid quae enim laborum amet quos repellendus consequuntur illum aliquam et ex. Voluptatibus, magnam commodi nemo accusantium voluptatum dolor non laboriosam nulla culpa deleniti distinctio doloremque fuga facere asperiores iste sint excepturi cum quia recusandae error praesentium! Corporis deserunt molestiae incidunt omnis dicta dolores veniam atque numquam quasi recusandae eveniet unde, alias cupiditate nobis, quisquam autem, cumque in! Praesentium asperiores, natus, itaque sequi repellat velit, sit in provident ex illum earum debitis dignissimos necessitatibus ab! Dicta officia nesciunt unde, placeat distinctio dolorum 
   Lorem, ipsum dolor sit amet consectetur adipisicing elit. Nesciunt facilis at cupiditate architecto perferendis cumque nulla, delectus possimus voluptatum? Unde.
   Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quisquam, modi?
   
    </div>
  )
}

export default About
